"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class Hyperparameter:
    """An algorithm hyperparameter with optional validation.

    Implemented as a python descriptor object.
    """
    def __init__(self, name, validate=..., validation_message=..., data_type=...) -> None:
        """Args:

        name (str): The name of this hyperparameter validate
        (callable[object]->[bool]): A validation function or list of validation
        functions.

            Each function validates an object and returns False if the object
            value is invalid for this hyperparameter.

        validation_message (str): A usage guide to display on validation
        failure.

        Args:
            name:
            validate:
            validation_message:
            data_type:
        """
        ...
    
    def validate(self, value):
        """Placeholder docstring"""
        ...
    
    def __get__(self, obj, objtype):
        """Placeholder docstring"""
        ...
    
    def __set__(self, obj, value):
        """Validate the supplied value and set this hyperparameter to value

        Args:
            obj:
            value:
        """
        ...
    
    def __delete__(self, obj):
        """Delete this hyperparameter

        Args:
            obj:
        """
        ...
    
    @staticmethod
    def serialize_all(obj):
        """Return all non-None ``hyperparameter`` values on ``obj`` as a ``dict[str,str].``

        Args:
            obj:
        """
        ...
    


