"""
This type stub file was generated by pyright.
"""

"""Placeholder docstring"""
def gt(minimum):
    """Placeholder docstring"""
    ...

def ge(minimum):
    """Placeholder docstring"""
    ...

def lt(maximum):
    """Placeholder docstring"""
    ...

def le(maximum):
    """Placeholder docstring"""
    ...

def isin(*expected):
    """Placeholder docstring"""
    ...

def istype(expected):
    """Placeholder docstring"""
    ...

