"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import
from enum import Enum
from sagemaker.interactive_apps.tensorboard import TensorBoardApp
from sagemaker.interactive_apps.detail_profiler_app import DetailProfilerApp

"""
This type stub file was generated by pyright.
"""
class SupportedInteractiveAppTypes(Enum):
    """SupportedInteractiveAppTypes indicates which apps are supported."""
    TENSORBOARD = ...


