"""
This type stub file was generated by pyright.
"""

from typing import Optional

"""
This type stub file was generated by pyright.
"""
logger = ...
class DetailProfilerApp:
    """Class for creating/accessing a DetailProfiler app hosted on SageMaker."""
    def __init__(self, region: Optional[str] = ...) -> None:
        """Initialize a DetailProfilerApp object.

        Args:
            region (str): The name of the region e.g. us-east-1. If not specified,
                one is created using the default AWS configuration chain.
        """
        ...
    
    def __str__(self) -> str:
        """Return str(self)."""
        ...
    
    def __repr__(self):
        """Return repr(self)."""
        ...
    
    def get_app_url(self, training_job_name: Optional[str] = ...):
        """Get an unsigned URL for DetailProfiler app hosted on SageMaker.

           For users that are already in SM Studio notebook instance, the method tries to
           get domain id and user profile from the Studio environment. If succeeded, the
           generated URL will direct to SM DetailProfiler app. Otherwise it will direct to
           DetailProfiler landing page on SageMaker console. For non Studio users, the
           URL will direct to the DetailProfiler landing page on SageMaker console.

        Args:
            training_job_name (str): Optional. The name of the training job to pre-load in
                DetailProfiler.
                If not provided, no job will be automatically loaded when the URL is opened.

        Returns:
            str: An unsigned URL for DetailProfiler hosted on SageMaker.
        """
        ...
    


