"""
This type stub file was generated by pyright.
"""

from typing import Optional
from sagemaker.explainer.clarify_explainer_config import ClarifyExplainerConfig

"""
This type stub file was generated by pyright.
"""
class ExplainerConfig:
    """A parameter to activate explainers."""
    def __init__(self, clarify_explainer_config: Optional[ClarifyExplainerConfig] = ...) -> None:
        """Initializes a config object to activate explainer.

        Args:
            clarify_explainer_config (:class:`~sagemaker.explainer.explainer_config.ClarifyExplainerConfig`):
                Optional. A config contains parameters for the SageMaker Clarify explainer. (Default: None)
        """
        ...
    


