"""
This type stub file was generated by pyright.
"""

from xml.sax import handler

class LoadParser(handler.ContentHandler):
    """ Extract headings from content.xml of an ODT file """
    triggers = ...
    def __init__(self, document) -> None:
        ...
    
    def characters(self, data):
        ...
    
    def startElementNS(self, tag, qname, attrs):
        ...
    
    def endElementNS(self, tag, qname):
        ...
    


