"""
This type stub file was generated by pyright.
"""

"""Custom Exceptions."""
class StepExecutionException(Exception):
    """Exception indicating a failure while execution pipeline steps."""
    def __init__(self, step_name, message) -> None:
        """Placeholder docstring"""
        ...
    


