"""
This type stub file was generated by pyright.
"""

"""Provides utilities for instantiating dependencies to boto-python objects."""
def suffix():
    """Generate a random string of length 4."""
    ...

def name(prefix):
    """Generate a new name with the specified prefix."""
    ...

def default_session():
    """Create a default session."""
    ...

