"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import
from sagemaker.huggingface.estimator import HuggingFace
from sagemaker.huggingface.model import HuggingFaceModel, HuggingFacePredictor
from sagemaker.huggingface.processing import HuggingFaceProcessor
from sagemaker.huggingface.llm_utils import get_huggingface_llm_image_uri
from sagemaker.huggingface.training_compiler.config import TrainingCompilerConfig

"""Placeholder docstring"""
