"""
This type stub file was generated by pyright.
"""

from typing import Dict, Optional
from sagemaker.jumpstart.enums import JumpStartScriptScope
from sagemaker.session import Session

"""
This type stub file was generated by pyright.
"""
logger = ...
def retrieve_default(region: Optional[str] = ..., model_id: Optional[str] = ..., model_version: Optional[str] = ..., tolerate_vulnerable_model: bool = ..., tolerate_deprecated_model: bool = ..., include_aws_sdk_env_vars: bool = ..., sagemaker_session: Session = ..., instance_type: Optional[str] = ..., script: JumpStartScriptScope = ...) -> Dict[str, str]:
    """Retrieves the default container environment variables for the model matching the arguments.

    Args:
        region (str): Optional. The AWS Region for which to retrieve the default environment
             variables. (Default: None).
        model_id (str): Optional. The model ID of the model for which to
            retrieve the default environment variables. (Default: None).
        model_version (str): Optional. The version of the model for which to retrieve the
            default environment variables. (Default: None).
        tolerate_vulnerable_model (bool): True if vulnerable versions of model
            specifications should be tolerated (exception not raised). If False, raises an
            exception if the script used by this version of the model has dependencies with known
            security vulnerabilities. (Default: False).
        tolerate_deprecated_model (bool): True if deprecated models should be tolerated
            (exception not raised). False if these models should raise an exception.
            (Default: False).
        include_aws_sdk_env_vars (bool): True if environment variables for low-level AWS API call
            should be included. The `Model` class of the SageMaker Python SDK inserts environment
            variables that would be required when making the low-level AWS API call.
            (Default: True).
        sagemaker_session (sagemaker.session.Session): A SageMaker Session
            object, used for SageMaker interactions. If not
            specified, one is created using the default AWS configuration
            chain. (Default: sagemaker.jumpstart.constants.DEFAULT_JUMPSTART_SAGEMAKER_SESSION).
        instance_type (str): An instance type to optionally supply in order to get environment
            variables specific for the instance type.
        script (JumpStartScriptScope): The JumpStart script for which to retrieve environment
            variables.
    Returns:
        dict: The variables to use for the model.

    Raises:
        ValueError: If the combination of arguments specified is not supported.
    """
    ...

