"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union
from sagemaker.workflow.entities import PipelineVariable

"""
This type stub file was generated by pyright.
"""
class MetadataProperties:
    """Accepts metadata properties parameters for conversion to request dict."""
    def __init__(self, commit_id: Optional[Union[str, PipelineVariable]] = ..., repository: Optional[Union[str, PipelineVariable]] = ..., generated_by: Optional[Union[str, PipelineVariable]] = ..., project_id: Optional[Union[str, PipelineVariable]] = ...) -> None:
        """Initialize a ``MetadataProperties`` instance and turn parameters into dict.

        # TODO: flesh out docstrings
        Args:
            commit_id (str or PipelineVariable):
            repository (str or PipelineVariable):
            generated_by (str or PipelineVariable):
            project_id (str or PipelineVariable):
        """
        ...
    


