"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class SessionSettings:
    """Optional container class for settings to apply to a SageMaker session."""
    def __init__(self, encrypt_repacked_artifacts=..., local_download_dir=..., include_jumpstart_tags=...) -> None:
        """Initialize the ``SessionSettings`` of a SageMaker ``Session``.

        Args:
            encrypt_repacked_artifacts (bool): Flag to indicate whether to encrypt the artifacts
                at rest in S3 using the default AWS managed KMS key for S3 when a custom KMS key
                is not provided (Default: True).
            local_download_dir (str): Optional. A path specifying the local directory
                for downloading artifacts. (Default: None).
            include_jumpstart_tags (bool): Optional. By default, if a JumpStart model is identified,
                it will receive special tags describing its properties.
        """
        ...
    
    @property
    def encrypt_repacked_artifacts(self) -> bool:
        """Return True if repacked artifacts at rest in S3 should be encrypted by default."""
        ...
    
    @property
    def local_download_dir(self) -> str:
        """Return path specifying the local directory for downloading artifacts."""
        ...
    
    @property
    def include_jumpstart_tags(self) -> bool:
        """Return True if JumpStart tags should be attached to models with JumpStart artifacts."""
        ...
    


