"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import
from sagemaker.workflow.entities import Expression
from sagemaker.workflow.parameters import ParameterString

"""
This type stub file was generated by pyright.
"""
def is_pipeline_variable(var: object) -> bool:
    """Check if the variable is a pipeline variable

    Args:
        var (object): The variable to be verified.
    Returns:
         bool: True if it is, False otherwise.
    """
    ...

def is_pipeline_parameter_string(var: object) -> bool:
    """Check if the variable is a pipeline parameter string

    Args:
        var (object): The variable to be verified.
    Returns:
         bool: True if it is, False otherwise.
    """
    ...

