"""
This type stub file was generated by pyright.
"""

from typing import List
from sagemaker.workflow.entities import RequestType

"""Pipeline Parallelism Configuration"""
class SelectiveExecutionConfig:
    """The selective execution configuration, which defines a subset of pipeline steps to run in

    another SageMaker pipeline run.
    """
    def __init__(self, selected_steps: List[str], source_pipeline_execution_arn: str = ..., reference_latest_execution: bool = ...) -> None:
        """Create a `SelectiveExecutionConfig`.

        Args:
            source_pipeline_execution_arn (str): The ARN from a reference execution of the
                current pipeline. Used to copy input collaterals needed for the selected
                steps to run. The execution status of the pipeline can be `Stopped`, `Failed`, or
                `Succeeded`.
            selected_steps (List[str]): A list of pipeline steps to run. All step(s) in all
                path(s) between two selected steps should be included.
            reference_latest_execution (bool): Whether to reference the latest execution if
                `source_pipeline_execution_arn` is not provided.
        """
        ...
    
    def to_request(self) -> RequestType:
        """Convert `SelectiveExecutionConfig` object to request dict."""
        ...
    


