"""
This type stub file was generated by pyright.
"""

from sagemaker.serverless.model import LambdaModel
from sagemaker.serverless.predictor import LambdaPredictor
from sagemaker.serverless.serverless_inference_config import ServerlessInferenceConfig

"""
This type stub file was generated by pyright.
"""
